modality: audio
mean_std_file: ./Auxiliary/Clean_Mean_Std.npy
class_per_split: ./Auxiliary/KOS_paper_splits.npy
ood: True

backbone:
  name: resnet12
  kwargs:
    keep_prob: 0.0
    avg_pool: True
    is_flatten: True
    maxpool_last2: True
    num_channels: 1
batch_size: 4
classifier:
  kwargs:
    feat_dim: 12800
    inner_param:
      lr: 0.01
      test_iter: 10
      train_iter: 5
  name: MAML
deterministic: true
device_ids: 0
episode_size: 1
epoch: 25
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/MAML.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 20
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.001
  name: Adam
  other: null
parallel_part:
- emb_func
port: 28138
pretrain_path: null
query_num: 10
rank: 0
result_root: ./results
resume: false
save_interval: 10
save_part:
- emb_func
seed: 0
shot_num: 1
tag: null
tb_scale: 3.3333333333333335
test_episode: 600
test_epoch: 5
test_query: 10
test_shot: 1
test_way: 5
train_episode: 2000
use_memory: false
way_num: 5
workers: 8
